# Generated by Django 3.2.6 on 2021-08-18 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=128, null=True, verbose_name='Krótki opis:')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='Napisz skąd jesteś:')),
                ('profile_image', models.ImageField(blank=True, default='account_pics/kaktus.jpg', null=True, upload_to='account_pics/', verbose_name='Zdjęcie profilowe:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
