# Generated by Django 3.2.6 on 2021-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='account_pics/kaktus.jpg', null=True, upload_to='account_pics/', verbose_name='Zdjęcie profilowe:    '),
        ),
    ]
