# Generated by Django 3.2.5 on 2021-08-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa przedmiotu:')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Opis:')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Cena:')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('negotiable', models.BooleanField(default=True, verbose_name='Do negocjacji')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='products_pics/')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offer')),
            ],
        ),
    ]
