# Generated by Django 3.2.5 on 2021-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210802_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(blank=True, default='products_pics/default.png', null=True, upload_to='products_pics/'),
        ),
    ]
