# Generated by Django 3.2.5 on 2021-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210806_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(blank=True, default='products_pics/default.png', null=True, upload_to='products_pics/', verbose_name='Dodaj zdjęcia:'),
        ),
    ]
