# Generated by Django 3.2.5 on 2021-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_offerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(blank=True, default='products_pics/default.png', null=True, upload_to='products_pics/', verbose_name='Dodaj zdjęcia:'),
        ),
    ]
