# Generated by Django 3.2.6 on 2021-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokalizacja:'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pet_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Roślina przyjazna zwierzętom:'),
        ),
    ]
