# Generated by Django 3.2.6 on 2021-08-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offergalleryimage',
            name='gallery_image',
            field=models.ImageField(default='products_pics/default.png', upload_to='products_pics/', verbose_name='  '),
        ),
        migrations.AlterField(
            model_name='offergalleryimage',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offer'),
        ),
        migrations.AlterField(
            model_name='offergalleryimage',
            name='offer_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offergalleryimage', to='home.offerimage'),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(default='products_pics/default.png', upload_to='products_pics/', verbose_name='  '),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offer'),
        ),
    ]
