# Generated by Django 3.2.6 on 2021-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='indoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina outdoorowa:'),
        ),
        migrations.AddField(
            model_name='offer',
            name='outdoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina indoorowa:'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pet_friendly',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina przyjazna zwierzętom:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='negotiable',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, verbose_name='Cena do negocjacji:'),
        ),
    ]
