# Generated by Django 3.2.6 on 2021-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210818_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='indoor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Roślina outdoorowa:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='Do negocjacji'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='outdoor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Roślina indoorowa:'),
        ),
    ]
