# Generated by Django 3.2.5 on 2021-08-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210817_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='offer_gallery_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offergalleryimage'),
        ),
    ]
