# Generated by Django 3.2.6 on 2021-09-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210918_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='indoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, verbose_name='Roślina outdoorowa:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='maintenance_category',
            field=models.CharField(choices=[('Roślina mało wymagająca', 'Roślina mało wymagająca'), ('Roślina średnio wymagająca', 'Roślina średnio wymagająca'), ('Roślina bardzo wymagająca', 'Roślina bardzo wymagająca')], default=('Roślina bardzo wymagająca', 'Roślina bardzo wymagająca'), max_length=64, verbose_name='Pielęgnacja rośliny:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='outdoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, verbose_name='Roślina indoorowa:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pet_friendly',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, verbose_name='Roślina przyjazna zwierzętom:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sprzedawca:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='size_category',
            field=models.CharField(choices=[('Roślina mała', 'Roślina mała'), ('Roślina średnia', 'Roślina średnia'), ('Roślina duża', 'Roślina duża'), ('Roślina bardzo duża', 'Roślina bardzo duża')], default=('Roślina bardzo duża', 'Roślina bardzo duża'), max_length=64, verbose_name='Wielkość rośliny:'),
        ),
    ]
