# Generated by Django 3.2.6 on 2021-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210825_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='indoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina outdoorowa:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='negotiable',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, verbose_name='Do negocjacji'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='outdoor',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina indoorowa:'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pet_friendly',
            field=models.BooleanField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=False, null=True, verbose_name='Roślina przyjazna zwierzętom:'),
        ),
    ]
