# Generated by Django 3.2.6 on 2021-08-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210830_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='pet_friendly',
            new_name='pet_friendlys',
        ),
    ]
