# Generated by Django 3.2.6 on 2021-08-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_pet_friendly_offer_pet_friendlys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='pet_friendlys',
            new_name='pet_friendly',
        ),
    ]
