# Generated by Django 3.2.5 on 2021-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210817_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Opis:'),
        ),
    ]
