# Generated by Django 3.2.5 on 2021-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='indoor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='outdoor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
