# Generated by Django 3.2.6 on 2021-08-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_pet_friendlys_offer_pet_friendly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='outdoor',
            new_name='outdoosr',
        ),
    ]
